---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls())
library(tidyverse)
library(lubridate)
library(Hmisc)
```

```{r}
f_prep_data <- function(filebase){
  test <- read.csv(paste0("../cleaned/", filebase, ".csv"), header = F)
  colnames(test) <- c("year", "month", "day", "hour", "minute", "second", "commit", "score")
  test <- test %>%
    mutate(date_time=make_datetime(year, month, day, hour, minute, second)) %>% 
    mutate(date=make_date(year, month, day)) %>% 
    mutate(week=week(date)) %>% 
    mutate(date_week=cut(date, "week")) %>% 
    mutate(date_2_week = round_date(date, "2 weeks"))
  return(test)
}
```

# Visualise banana example
```{r}
test <- f_prep_data("mcmc_banana_AdaptiveCovarianceMCMC_1")
test %>% 
  ggplot(aes(x=date_2_week, y=score)) +
  geom_jitter() +
  theme_classic() +
  geom_smooth() +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```

```{r}
test %>% 
  ggplot(aes(x=date_time, y=kld)) +
  geom_line()
```



Fit change point model to data
```{r}
library(changepoint)
model  <- cpt.mean(test$score)
plot(model)
model@param.est
```

# Visualise normal DE MCMC
```{r}
test <- f_prep_data("mcmc_normal_DifferentialEvolutionMCMC_3")
test %>% 
  ggplot(aes(x=date_2_week, y=kld, group=as.factor(date_2_week))) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(alpha=0.4) +
  theme_classic()
```
```{r}
model  <- cpt.mean(test$kld,method = "PELT", minseglen = 10)
plot(model)
summary(model)
```
# normal population MCMC
```{r}
test <- f_prep_data("mcmc_normal_PopulationMCMC_1")
test %>% 
  ggplot(aes(x=date_2_week, y=kld)) +
  geom_boxplot(aes(group=as.factor(date_2_week)), outlier.shape = NA) +
  geom_jitter(alpha=0.4) +
  theme_classic()  +
  geom_smooth(colour="blue")
```

```{r}
model  <- cpt.mean(test$kld,method = "PELT", minseglen = 10)
plot(model)
summary(model)
```

HMC
```{r}
test <- f_prep_data("mcmc_normal_HamiltonianMCMC_1")

test %>% 
  ggplot(aes(x=date_2_week, y=score)) +
  geom_boxplot(aes(group=as.factor(date_2_week)), outlier.shape = NA) +
  geom_jitter(alpha=0.4) +
  theme_classic() +
  scale_y_log10() +
  geom_smooth(colour="blue")
```

```{r}
model  <- cpt.mean(test$kld,method = "PELT")
plot(model)
summary(model)
```


# Optimiser results
```{r}
test <- f_prep_data("opt_fn_SNES")

library(zoo)
test$kld_mean <- rollmean(test$score, 20, fill = list(NA, NULL, NA))


test %>% 
  ggplot(aes(x=date_2_week, y=score)) +
  geom_boxplot(aes(group=as.factor(date_2_week)), outlier.shape = NA) +
  geom_jitter(alpha=0.4) +
  theme_classic() +
  scale_y_log10() +
  geom_smooth(colour="blue")
```

```{r}
model  <- cpt.mean(test$kld,method = "PELT", minseglen = 100)
plot(model)
summary(model)
```

```{r}
test <- f_prep_data("opt_fn_XNES")

test %>% 
  ggplot(aes(x=date_2_week, y=kld)) +
  geom_jitter(alpha=0.4) +
  theme_classic() +
  scale_y_log10() +
  geom_smooth(colour="blue") +
  stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")
```
```{r}
model  <- cpt.mean(test$kld,method = "PELT", minseglen = 120)
plot(model)
summary(model)
```

```{r}
test <- f_prep_data("opt_logistic_SNES")

test %>% 
  ggplot(aes(x=date_2_week, y=kld)) +
  geom_boxplot(aes(group=as.factor(date_2_week)), outlier.shape = NA) +
  geom_jitter(alpha=0.4) +
  theme_classic() +
  scale_y_log10() +
  geom_smooth(colour="blue")
```

```{r}
test %>% 
  ggplot(aes(x=date_2_week, y=kld)) +
  geom_line() +
  theme_classic() +
  scale_y_log10() +
  geom_smooth(colour="blue")
```



```{r}
model  <- cpt.mean(test$kld,method = "PELT", minseglen = 100)
plot(model)
summary(model)
```